language: bash


before_script:

  # Install "shunit2"

  # Note sure where to find the most dependable source for "shunit2". Try this:

  - git clone https://github.com/kward/shunit2 shunit2

python:
  - "3.5"


before_install:
  - sudo apt-get install python3 python3-pip #(necessary if language!=python)
  - sudo apt-get remove python2 python2-pip  #(necessary if language!=python)
  - python --version
  - sudo pip install --upgrade pip   # (not sure if this is necessary)


install:
  #- pip install .   # Build fails "Permission denied".  Try using sudo:
  - sudo pip install .
  #- sudo pip install -r requirements.txt


# commands to run tests

script:
  - bash tests/test_read_coords_pdb.sh
  - bash tests/test_ltemplify.sh
  - bash tests/test_oplsaa.sh
  - bash tests/test_compass.sh
  - python tests/test_genpoly_lt.py


# Thanks to Kate Ward (shunit2), Martin Seener, Davi Ortega, and Shyam Saladi:
# https://github.com/kward/shunit2
# https://www.sysorchestra.com/2014/10/12/travisshunit2/
